import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Profile from "./components/Profile/Profile";
import Search from "./components/Search/Search";
import styles from "./page.module.css"
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "First Next Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>



    <div className={styles.container}>
        <header>
          <nav className={styles.nav}>

            <div className={styles.title}>
              <Link href="/"><h1 className={styles.header_title}>Code With Amboka</h1></Link>
              <sub className={styles.sub_text}>Build something great!</sub>
            </div>

              <div className="search">
                <Search />
              </div>

              <div className="profile">
                <Profile />
              </div>

          </nav>
        </header>
    </div>
        {children}
        </body>
    </html>
  );
}
